// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Ambiq
/*
 * The TypeScript extractor: a TypeDoc JSON dump in, a reference model out.
 *
 * TypeDoc's `--json` output is a serialized `ProjectReflection`, a tree of
 * reflections identified by a numeric `kind` out of its `ReflectionKind` enum
 * and tagged with a `schemaVersion`. The version is read from the dump and
 * recorded rather than pinned, the way the Doxygen reader takes its version
 * from `index.xml`: a reference generated by a newer TypeDoc should say so.
 *
 * Everything that knows about TypeScript stops at this file. It walks the
 * reflections, rebuilds declarations the way TypeScript spells them, and folds
 * TSDoc's block tags onto the fields of `reference-model.ts`. What routes the
 * pages, resolves cross-references and writes MDX is in `reference-render.mjs`
 * and never sees a reflection, which is the point: the Python, C and
 * TypeScript references are the same pages with different content.
 *
 * The mapping, in one place:
 *
 *   project (kind 1)              root module   the package itself
 *   module (kind 2)               module        one page per entry point
 *   namespace (kind 4)            module        nested under its container
 *   class (kind 128)              class         members nested under it
 *   interface (kind 256)          type          members nested under it
 *   type alias (kind 2097152)     type          same kind a C typedef takes
 *   enum (kind 8)                 enum          its members become constants
 *   enum member (kind 16)         constant
 *   function (kind 64)            function
 *   method (kind 2048)            method
 *   constructor (kind 512)        method
 *   property (kind 1024)          attribute
 *   accessor (kind 262144)        attribute     documented off its getter
 *   variable (kind 32)            constant      attribute when not `const`
 *   reference (kind 4194304)      dropped       a re-export of a symbol that
 *   document (kind 8388608)       dropped       is documented where it is
 *
 * `extractModel` is a pure function of the parsed dump and the options, so the
 * CLI and the tests exercise the same code. `readTypedocJson` is the one place
 * that touches the filesystem.
 */

import { readFile } from 'node:fs/promises';

/** The TypeDoc JSON schema this reader was written against. */
export const TYPEDOC_SCHEMA_VERSION = '2.0';

/** Wrap a declaration across lines past this width, as the other two do. */
const LINE_LENGTH = 120;

/** Frontmatter descriptions are a summary, not the first paragraph. */
const DESCRIPTION_LIMIT = 160;

/** TypeDoc's `ReflectionKind`, as the JSON spells it. */
const KIND = {
  project: 1,
  module: 2,
  namespace: 4,
  enum: 8,
  enumMember: 16,
  variable: 32,
  function: 64,
  class: 128,
  interface: 256,
  constructor: 512,
  property: 1024,
  method: 2048,
  accessor: 262144,
  typeAlias: 2097152,
  reference: 4194304,
  document: 8388608,
};

/** Reflection kinds that become a page of their own. */
const MODULE_KINDS = new Set([KIND.module, KIND.namespace]);

/** Reflection kinds that become a symbol, and the model kind each takes. */
const SYMBOL_KINDS = new Map([
  [KIND.class, 'class'],
  /* An interface and a type alias are both "a name for a shape" and the model
   * spells that `type`, the same word a C typedef lands on. */
  [KIND.interface, 'type'],
  [KIND.typeAlias, 'type'],
  [KIND.enum, 'enum'],
  [KIND.enumMember, 'constant'],
  [KIND.function, 'function'],
  [KIND.method, 'method'],
  [KIND.constructor, 'method'],
  [KIND.property, 'attribute'],
  [KIND.accessor, 'attribute'],
  [KIND.variable, 'constant'],
]);

/** Reflection kinds that are deliberately not published. */
const DROPPED_KINDS = new Set([KIND.reference, KIND.document]);

/** Inline tags that name another symbol rather than carrying prose. */
const LINK_TAGS = new Set(['@link', '@linkcode', '@linkplain']);

/**
 * The extraction half of the options. The half that decides how a reference
 * looks lives in `RENDER_DEFAULTS`.
 */
export const DEFAULTS = {
  /** Strip this prefix from the paths TypeDoc recorded. */
  sourceRoot: '',
  /** Link template for source, with `{path}` and `{line}`. */
  sourceUrl: '',
  /** The library the reference documents. Empty takes TypeDoc's package name. */
  name: '',
};

export class TsrefSchemaError extends Error {}

const schemaHint =
  'The file must be what `typedoc --json <file>` wrote: a serialized ProjectReflection.';

/* -------------------------------------------------------------------------
 * Reading the dump
 * ---------------------------------------------------------------------- */

/**
 * Check that a parsed JSON value is a TypeDoc project reflection.
 *
 * @param {unknown} value Parsed `typedoc --json` output.
 * @param {string} [label] What to call the input in an error message.
 * @returns {object} The same value, typed as a project reflection.
 * @throws {TsrefSchemaError} when this is not a TypeDoc dump.
 */
export function parseTypedocJson(value, label = 'The JSON') {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    throw new TsrefSchemaError(`${label} is not an object. ${schemaHint}`);
  }
  if (value.kind !== KIND.project && value.variant !== 'project') {
    throw new TsrefSchemaError(
      `${label} has kind ${JSON.stringify(value.kind)}, expected ${KIND.project}. ${schemaHint}`,
    );
  }
  if (!Array.isArray(value.children) || value.children.length === 0) {
    throw new TsrefSchemaError(
      `${label} has no children, so TypeDoc documented nothing. ${schemaHint}`,
    );
  }
  return value;
}

/**
 * Read a `typedoc --json` file.
 *
 * @param {string} file Path to the JSON TypeDoc wrote.
 * @returns {Promise<object>} The project reflection.
 * @throws {TsrefSchemaError} when the file is missing or is not a dump.
 */
export async function readTypedocJson(file) {
  let text;
  try {
    text = await readFile(file, 'utf8');
  } catch (error) {
    throw new TsrefSchemaError(`Could not read ${file}: ${error.message}`);
  }
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (error) {
    throw new TsrefSchemaError(`${file} is not JSON: ${error.message}`);
  }
  return parseTypedocJson(parsed, file);
}

/* -------------------------------------------------------------------------
 * Small shared helpers
 * ---------------------------------------------------------------------- */

const collapse = (text) => String(text ?? '').replace(/\s+/g, ' ');

/** Drop a key whose value is empty, so the model carries no `"type": ""`. */
const withOptional = (base, extras) => {
  const out = { ...base };
  for (const [key, value] of Object.entries(extras)) {
    if (value !== undefined && value !== null && value !== '') out[key] = value;
  }
  return out;
};

/** A path segment that survives being split back out of a dotted module path. */
const segment = (text) =>
  String(text)
    .replace(/[^\w.-]+/g, '-')
    .replace(/\./g, '_')
    .replace(/^-+|-+$/g, '') || 'x';

/** The first sentence of a description, for the member index and frontmatter. */
export function summarize(text) {
  const plain = collapse(String(text ?? '').split(/\n\s*\n/)[0])
    .replace(/^#+\s*/, '')
    .replace(/[*`_]/g, '')
    .trim();
  const sentence = /^(.*?[.!?])(\s|$)/.exec(plain)?.[1] ?? plain;
  return sentence.length > DESCRIPTION_LIMIT
    ? `${sentence.slice(0, DESCRIPTION_LIMIT - 1).trimEnd()}…`
    : sentence;
}

/* -------------------------------------------------------------------------
 * Types
 * ---------------------------------------------------------------------- */

/** Types that need parentheses when they sit inside another type. */
const COMPOUND = new Set([
  'union',
  'intersection',
  'conditional',
  'reflection',
]);

const wrapped = (type) => {
  const text = typeText(type);
  return COMPOUND.has(type?.type) && /[|&?]|=>/.test(text) ? `(${text})` : text;
};

/** A type literal: a call signature, an object shape, or neither. */
function reflectionType(declaration) {
  if (!declaration) return 'object';
  const signature = declaration.signatures?.[0];
  if (signature) {
    const args = (signature.parameters ?? []).map(paramText).join(', ');
    return `(${args}) => ${typeText(signature.type) || 'void'}`;
  }
  const fields = (declaration.children ?? []).map(
    (child) =>
      `${child.name}${child.flags?.isOptional ? '?' : ''}: ${typeText(child.type)}`,
  );
  return fields.length > 0 ? `{ ${fields.join('; ')} }` : 'object';
}

/**
 * A TypeDoc type as the source text a reader would write.
 *
 * TypeDoc keeps a structured type rather than the text the declaration used,
 * so the text has to be rebuilt. That is a feature for the model: an inferred
 * return type gets spelled out instead of being absent, which is what the
 * reader wanted to know.
 *
 * @param {object} [type] A TypeDoc type node.
 * @returns {string} The type as TypeScript source, or an empty string.
 */
export function typeText(type) {
  if (!type) return '';
  switch (type.type) {
    case 'intrinsic':
    case 'unknown':
      return String(type.name ?? '');
    case 'reference': {
      const args = (type.typeArguments ?? []).map(typeText);
      return `${type.name}${args.length > 0 ? `<${args.join(', ')}>` : ''}`;
    }
    case 'literal':
      if (typeof type.value === 'string') return JSON.stringify(type.value);
      if (type.value === null) return 'null';
      /* A bigint literal is serialized as `{ value, negative }`, because JSON
       * has no bigint to round-trip it through. */
      if (typeof type.value === 'object')
        return `${type.value.negative ? '-' : ''}${type.value.value}n`;
      return String(type.value);
    case 'union':
      return (type.types ?? []).map(wrapped).join(' | ');
    case 'intersection':
      return (type.types ?? []).map(wrapped).join(' & ');
    case 'array':
      return `${wrapped(type.elementType)}[]`;
    case 'tuple':
      return `[${(type.elements ?? []).map(typeText).join(', ')}]`;
    case 'namedTupleMember':
      return `${type.name}${type.isOptional ? '?' : ''}: ${typeText(type.element)}`;
    case 'optional':
      return `${wrapped(type.elementType)}?`;
    case 'rest':
      return `...${typeText(type.elementType)}`;
    case 'typeOperator':
      return `${type.operator} ${wrapped(type.target)}`;
    case 'query':
      return `typeof ${typeText(type.queryType)}`;
    case 'predicate':
      return type.targetType
        ? `${type.asserts ? 'asserts ' : ''}${type.name} is ${typeText(type.targetType)}`
        : `asserts ${type.name}`;
    case 'indexedAccess':
      return `${typeText(type.objectType)}[${typeText(type.indexType)}]`;
    case 'conditional':
      return `${typeText(type.checkType)} extends ${typeText(type.extendsType)} ? ${typeText(type.trueType)} : ${typeText(type.falseType)}`;
    case 'inferred':
      return `infer ${type.name}`;
    case 'mapped':
      return `{ [${type.parameter} in ${typeText(type.parameterType)}]: ${typeText(type.templateType)} }`;
    case 'templateLiteral':
      return `\`${type.head ?? ''}${(type.tail ?? [])
        .map(([inner, text]) => `\${${typeText(inner)}}${text}`)
        .join('')}\``;
    case 'reflection':
      return reflectionType(type.declaration);
    default:
      return String(type.name ?? '');
  }
}

/** `<T extends U = V>`, when a declaration has type parameters. */
function typeParamsText(list) {
  if (!list || list.length === 0) return '';
  const parts = list.map((entry) =>
    [
      entry.varianceModifier ? `${entry.varianceModifier} ` : '',
      entry.name,
      entry.type ? ` extends ${typeText(entry.type)}` : '',
      entry.default ? ` = ${typeText(entry.default)}` : '',
    ].join(''),
  );
  return `<${parts.join(', ')}>`;
}

/** One parameter as it is written in a declaration. */
function paramText(param) {
  const rest = param.flags?.isRest ? '...' : '';
  /* `?` and `= value` are alternatives in TypeScript: a parameter with a
   * default is already optional and spelling both is a syntax error. */
  const optional =
    param.flags?.isOptional && param.defaultValue === undefined ? '?' : '';
  const type = typeText(param.type);
  const value =
    param.defaultValue === undefined ? '' : ` = ${param.defaultValue}`;
  return `${rest}${param.name}${optional}${type ? `: ${type}` : ''}${value}`;
}

/**
 * A callable declaration, wrapped one parameter per line when the single-line
 * form would run past the line length.
 */
function callableSignature(lead, signature) {
  const args = (signature.parameters ?? []).map(paramText);
  const head = `${lead}${typeParamsText(signature.typeParameters)}`;
  const returns = typeText(signature.type);
  const tail = returns ? `: ${returns}` : '';
  const oneLine = `${head}(${args.join(', ')})${tail}`;
  if (oneLine.length <= LINE_LENGTH || args.length === 0) return oneLine;
  return `${head}(\n${args.map((arg) => `  ${arg},`).join('\n')}\n)${tail}`;
}

/** `static `, `readonly `, and the rest of what a member's flags say aloud. */
const modifiers = (flags = {}) =>
  [
    flags.isAbstract ? 'abstract' : '',
    flags.isStatic ? 'static' : '',
    flags.isReadonly ? 'readonly' : '',
  ]
    .filter(Boolean)
    .join(' ');

/** The declaration text for one reflection, in the language's own spelling. */
function declarationText(node, kind, signature) {
  const prefix = modifiers(node.flags);
  const lead = prefix ? `${prefix} ` : '';
  switch (node.kind) {
    case KIND.function:
      return callableSignature(`function ${node.name}`, signature ?? {});
    case KIND.method:
      return callableSignature(`${lead}${node.name}`, signature ?? {});
    case KIND.constructor:
      return callableSignature('constructor', signature ?? {});
    case KIND.class:
    case KIND.interface: {
      const word = node.kind === KIND.class ? 'class' : 'interface';
      const extended = (node.extendedTypes ?? []).map(typeText);
      const implemented = (node.implementedTypes ?? []).map(typeText);
      return [
        `${lead}${word} ${node.name}${typeParamsText(node.typeParameters)}`,
        extended.length > 0 ? ` extends ${extended.join(', ')}` : '',
        implemented.length > 0 ? ` implements ${implemented.join(', ')}` : '',
      ].join('');
    }
    case KIND.typeAlias:
      return `type ${node.name}${typeParamsText(node.typeParameters)} = ${typeText(node.type)}`;
    case KIND.enum:
      return `enum ${node.name}`;
    case KIND.enumMember: {
      const value = typeText(node.type);
      return value ? `${node.name} = ${value}` : node.name;
    }
    case KIND.variable: {
      const keyword = node.flags?.isConst === false ? 'let' : 'const';
      const type = typeText(node.type);
      /* TypeScript infers a `const` initialized to a literal as that literal's
       * own type, so TypeDoc reports `const MAX: 1048576`. Spelling both the
       * type and the value tells the reader the same number twice. */
      const annotation = type && type !== node.defaultValue ? `: ${type}` : '';
      return [
        `${keyword} ${node.name}`,
        annotation,
        node.defaultValue === undefined ? '' : ` = ${node.defaultValue}`,
      ].join('');
    }
    case KIND.accessor: {
      const getter = node.getSignature;
      if (getter) return callableSignature(`${lead}get ${node.name}`, getter);
      const setter = node.setSignature;
      if (setter) return callableSignature(`${lead}set ${node.name}`, setter);
      return `${lead}${node.name}`;
    }
    default: {
      const type = typeText(node.type);
      const optional = node.flags?.isOptional ? '?' : '';
      return `${lead}${node.name}${optional}${type ? `: ${type}` : ''}`;
    }
  }
}

/* -------------------------------------------------------------------------
 * Comments
 * ---------------------------------------------------------------------- */

/**
 * TypeDoc comment parts as Markdown.
 *
 * `text` and `code` parts are already Markdown -- TypeDoc splits a comment on
 * code spans and fences but does not strip their markers -- so they pass
 * through. An inline `{@link Foo}` becomes the identifier in a code span: the
 * model has no cross-reference field, and TypeDoc's `target` is a reflection
 * id rather than a model id, so it cannot become a link here without the
 * renderer learning about TypeDoc. Cross-references written in the model's own
 * `[Text][symbol_id]` syntax do resolve, in the renderer.
 *
 * @param {object[]} [parts] A `comment.summary` or a block tag's `content`.
 * @returns {string} Markdown.
 */
export function renderComment(parts) {
  let out = '';
  for (const part of parts ?? []) {
    if (part.kind === 'inline-tag') {
      out += LINK_TAGS.has(part.tag)
        ? `\`${collapse(part.text).trim()}\``
        : (part.text ?? '');
      continue;
    }
    out += part.text ?? '';
  }
  return out;
}

/** A tag name as a title: `@defaultValue` reads "Default value". */
const tagTitle = (tag) =>
  tag
    .replace(/^@/, '')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/^./, (first) => first.toUpperCase());

/** A `{Type}` or a leading `` `Type` `` in front of a `@throws` description. */
const BRACED_TYPE = /^\{([^}]+)\}\s*/;
const LEADING_CODE = /^`([A-Z][\w.]*)`[\s,.]/;

function throwEntry(body) {
  const braced = BRACED_TYPE.exec(body);
  if (braced) {
    return withOptional(
      { description: body.slice(braced[0].length).trim() },
      { type: braced[1].trim() },
    );
  }
  /* `@throws {@link RangeError} when ...` reaches here with the link already
   * rendered as a code span. Only an identifier-shaped span is taken as the
   * type, so a description that opens with `input` keeps its first word. */
  const leading = LEADING_CODE.exec(body);
  if (leading) {
    return withOptional(
      { description: body.slice(leading[0].length - 1).trim() },
      { type: leading[1] },
    );
  }
  return { description: body };
}

const FENCE = /(^|\n)```([^\n]*)\n([\s\S]*?)```/;

/**
 * An `@example` block as an example.
 *
 * TSDoc's convention is prose then a fenced block, so the prose introduces the
 * snippet that follows it. A block with no fence at all is code: that is how
 * `@example` was written before TypeDoc required the fence, and reading it as
 * prose would produce an example with no code.
 */
function exampleEntry(body, language) {
  const match = FENCE.exec(body);
  if (!match) return withOptional({ code: body.trim() }, { language });
  const before = body.slice(0, match.index).trim();
  return withOptional(
    { code: match[3].replace(/\s+$/, '') },
    { language: match[2].trim() || language, description: before || undefined },
  );
}

/**
 * One comment, split into prose and model fields.
 *
 * @returns {{ description: string, summary: string, fields: object }}
 */
function document(comment, context) {
  const fields = {
    params: new Map(),
    returns: [],
    raises: [],
    examples: [],
    since: undefined,
    deprecated: undefined,
  };
  const summaryText = renderComment(comment?.summary).trim();
  const prose = [summaryText];
  const notes = [];

  for (const tag of comment?.blockTags ?? []) {
    const body = renderComment(tag.content).trim();
    switch (tag.tag) {
      case '@param':
        /* TypeDoc normally moves a `@param` onto the parameter it names, but a
         * name it could not match stays here, and an older dump keeps them
         * all. Both are read, and an unmatched one is reported below. */
        if (tag.name) fields.params.set(tag.name, body);
        else context.warn('a @param entry has no name');
        break;
      case '@returns':
      case '@return':
        fields.returns.push({ description: body });
        break;
      case '@throws':
      case '@throw':
      case '@exception':
        fields.raises.push(throwEntry(body));
        break;
      case '@since':
        fields.since = collapse(body).trim();
        break;
      case '@deprecated':
        fields.deprecated = body;
        break;
      case '@example':
        fields.examples.push(exampleEntry(body, context.language));
        break;
      case '@remarks':
      case '@privateRemarks':
        if (tag.tag === '@remarks' && body) prose.push(body);
        break;
      default:
        if (body) notes.push(`:::note[${tagTitle(tag.tag)}]\n${body}\n\n:::`);
    }
  }

  /* `@deprecated` with no prose is a modifier rather than a block tag, and the
   * model wants a sentence either way because that is all the reader sees. */
  if (
    !fields.deprecated &&
    (comment?.modifierTags ?? []).includes('@deprecated')
  )
    fields.deprecated = 'Deprecated.';

  return {
    description: [...prose, ...notes].filter(Boolean).join('\n\n'),
    summary: summarize(summaryText),
    fields,
  };
}

/* -------------------------------------------------------------------------
 * Symbols
 * ---------------------------------------------------------------------- */

/** A path TypeDoc recorded, made relative to the repository it came from. */
function locationPath(file, options) {
  const normalized = String(file ?? '').replace(/\\/g, '/');
  if (options.sourceRoot && normalized.startsWith(options.sourceRoot)) {
    return normalized.slice(options.sourceRoot.length).replace(/^\/+/, '');
  }
  return normalized.replace(/^\/+/, '');
}

/**
 * Where a reflection is written.
 *
 * TypeDoc records its own `url` when it resolved a git remote. `--source-url`
 * wins over it, because the caller knows which host is publishing and TypeDoc
 * only knows which one the build machine cloned from.
 */
function sourceOf(node, context, fallback) {
  const entry = (node.sources ?? [])[0];
  if (!entry) return fallback ?? { path: '', line: 1 };
  const path = locationPath(entry.fileName, context.options);
  const line = Number.isInteger(entry.line) && entry.line > 0 ? entry.line : 1;
  return withOptional(
    { path, line },
    {
      url: context.options.sourceUrl
        ? context.options.sourceUrl
            .replace('{path}', path)
            .replace('{line}', String(line))
        : entry.url,
    },
  );
}

/** The model kind a reflection takes, or null when it is not published. */
function modelKind(node) {
  if (node.kind === KIND.variable) {
    /* A `let` or `var` export is mutable state, which is an attribute; only a
     * `const` is the fixed value the word "constant" promises. */
    return node.flags?.isConst === false ? 'attribute' : 'constant';
  }
  return SYMBOL_KINDS.get(node.kind) ?? null;
}

/** Members of a class, interface or enum, in the order the dump lists them. */
function memberSymbols(node, context, scope) {
  const out = [];
  for (const child of node.children ?? []) {
    /* TypeDoc marks what it was told to hide rather than omitting it, so a
     * private member reaches the dump and is declined here. */
    if (child.flags?.isPrivate || child.flags?.isExternal) continue;
    const symbol = symbolOf(child, context, scope);
    if (symbol) out.push(symbol);
  }
  return out;
}

/**
 * One reflection as a model symbol.
 *
 * @param {object} node The reflection.
 * @param {object} context Options, language and the warning sink.
 * @param {string} scope The dotted id of whatever contains it.
 * @returns {object|null} The symbol, or null when the kind is not published.
 */
function symbolOf(node, context, scope) {
  if (DROPPED_KINDS.has(node.kind)) return null;
  const kind = modelKind(node);
  if (!kind) {
    context.warn(`unsupported reflection kind ${node.kind} on "${node.name}"`);
    return null;
  }

  const id = scope ? `${scope}.${node.name}` : node.name;
  const inner = context.scoped(id);

  /* A callable carries its documentation on the signature, not on the
   * declaration, because two overloads have two sets of parameters and two
   * comments. The first is documented and the rest are reported: the model has
   * one signature per symbol, and inventing ids for the others would give the
   * page anchors nobody writes a link against. */
  const signatures = node.signatures ?? [];
  if (signatures.length > 1) {
    inner.warn(
      `has ${signatures.length} overloads; the first one is documented`,
    );
  }
  const signature = signatures[0] ?? node.getSignature ?? node.setSignature;
  const comment = signature?.comment ?? node.comment;
  const { description, summary, fields } = document(comment, inner);

  /* The declaration is the authority on which parameters exist and what they
   * are typed; the comment is the authority on what they mean. A documented
   * name the declaration does not have is a stale comment, and it is reported
   * rather than added as a row for an argument nobody can pass. */
  const declared = signature?.parameters ?? [];
  const params = declared.map((param) => {
    const inlineText = renderComment(param.comment?.summary).trim();
    return withOptional(
      {
        name: param.name,
        description: inlineText || fields.params.get(param.name) || '',
      },
      { type: typeText(param.type), default: param.defaultValue },
    );
  });
  for (const documented of fields.params.keys()) {
    if (!declared.some((param) => param.name === documented))
      inner.warn(`documents a parameter "${documented}" it does not declare`);
  }

  const source = sourceOf(
    node,
    context,
    signature && sourceOf(signature, context),
  );
  const returns = fields.returns.map((entry) =>
    withOptional(entry, { type: typeText(signature?.type) }),
  );

  return withOptional(
    {
      id,
      name: node.name,
      kind,
      language: context.language,
      signature: declarationText(node, kind, signature),
      summary,
      description,
      params,
      returns,
      raises: fields.raises,
      examples: fields.examples,
      source,
      members: memberSymbols(node, inner, id),
    },
    { since: fields.since, deprecated: fields.deprecated },
  );
}

/* -------------------------------------------------------------------------
 * Modules
 * ---------------------------------------------------------------------- */

/**
 * Turn a parsed TypeDoc dump into a reference model.
 *
 * @param {object} project From {@link parseTypedocJson} or {@link readTypedocJson}.
 * @param {object} [options] Extraction options; see {@link DEFAULTS}.
 * @param {object} [meta] What the caller knows that the dump cannot say:
 *   `sourceCommit`, and the `$schema` the artifacts carry.
 * @returns {{ model: object, warnings: string[] }}
 */
export function extractModel(project, options = DEFAULTS, meta = {}) {
  const resolved = { ...DEFAULTS, ...options };
  const warnings = [];
  const language = 'typescript';
  /* A warning names the symbol it came from, so every context carries the
   * factory that makes the next one: a member reads its own documentation and
   * reports against its own id rather than against whichever page it was
   * reached through. */
  const scoped = (subject) => ({
    options: resolved,
    language,
    scoped,
    warn: (message) => warnings.push(`${subject}: ${message}`),
  });

  const rootName =
    resolved.name || project.packageName || project.name || 'reference';
  const documented = document(project.comment, scoped(rootName));
  const root = {
    path: segment(rootName),
    name: rootName,
    summary: documented.summary,
    description: documented.description,
    symbols: [],
    submodules: [],
  };

  /**
   * Create the intermediate modules a nested route needs, once each.
   *
   * An entry point named `sensors/imu` is two levels of route, the same way a
   * dotted Python package is, so the name is split rather than flattened into
   * one segment nobody can navigate.
   */
  const byPath = new Map([[root.path, root]]);
  const ensure = (parent, parentScope, name) => {
    const parts = String(name).split('/').filter(Boolean);
    let node = parent;
    let path = parent.path;
    let scope = parentScope;
    for (const [depth, part] of parts.entries()) {
      path = `${path}.${segment(part)}`;
      scope = `${scope}.${part}`;
      let next = byPath.get(path);
      if (!next) {
        next = {
          path,
          name: depth === parts.length - 1 ? name : part,
          summary: '',
          description: '',
          symbols: [],
          submodules: [],
        };
        byPath.set(path, next);
        node.submodules.push(next);
      }
      node = next;
    }
    return { module: node, scope };
  };

  /** Fill one module from the reflection that produced it, children and all. */
  const fill = (module, node, scope) => {
    const docs = document(node.comment, scoped(module.path));
    if (!module.description) {
      module.summary = docs.summary;
      module.description = docs.description;
    }
    for (const child of node.children ?? []) {
      if (child.flags?.isPrivate || child.flags?.isExternal) continue;
      if (MODULE_KINDS.has(child.kind)) {
        const nested = ensure(module, scope, child.name);
        fill(nested.module, child, nested.scope);
        continue;
      }
      const symbol = symbolOf(child, scoped(scope), scope);
      if (symbol) module.symbols.push(symbol);
    }
  };

  /* A single-entry-point run hangs the symbols straight off the project, and a
   * multi-entry one puts a module in between. Both shapes land on the same
   * tree: the root module is the package either way. */
  fill(root, project, rootName);

  /* An id is the page anchor, so two symbols cannot share one. Two entry
   * points that export the same name genuinely do, and qualifying the later
   * one by its page keeps both reachable. */
  const seen = new Set();
  for (const module of byPath.values()) {
    const visit = (symbol) => {
      if (seen.has(symbol.id)) {
        warnings.push(`${module.path}: duplicate id ${symbol.id}`);
        symbol.id = `${module.path}::${symbol.id}`;
      }
      seen.add(symbol.id);
      for (const member of symbol.members) visit(member);
    };
    for (const symbol of module.symbols) visit(symbol);
  }

  /* An entry point that exported nothing but re-exports has nothing to show. */
  const prune = (module) => {
    module.submodules = module.submodules.filter(prune);
    return (
      module === root ||
      module.symbols.length > 0 ||
      module.submodules.length > 0 ||
      Boolean(module.description)
    );
  };
  prune(root);

  const model = withOptional(
    { name: rootName, language, modules: [root] },
    {
      $schema: meta.schema,
      generatedFrom: withOptional(
        {
          tool: 'tsref',
          version: project.schemaVersion || TYPEDOC_SCHEMA_VERSION,
        },
        { sourceCommit: meta.sourceCommit },
      ),
    },
  );

  return { model, warnings };
}
