// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Ambiq
/*
 * Which heading a page sits under in llms.txt.
 *
 * The sidebar is the site's own statement of how its pages are grouped, so the
 * text artifacts repeat it rather than invent a second grouping. The fixture
 * here is a sidebar in the shape Starlight accepts, including the
 * `autogenerate` entry a site reaches for once a directory outgrows a hand
 * written list: pages under one of those are the reason this file exists.
 */

import assert from 'node:assert/strict';
import { test } from 'node:test';

import { sidebarTrails, trailFor } from '../starlight/discoverability.ts';

const sidebar = [
  { label: 'Overview', slug: '' },
  {
    label: 'Guides',
    collapsed: false,
    items: [
      { label: 'Getting started', slug: 'guides/start' },
      { autogenerate: { directory: 'guides/kernels', collapsed: true } },
    ],
  },
  {
    label: 'Reference',
    items: [{ autogenerate: { directory: 'reference' } }],
  },
  { label: 'Changelog', link: '/docs/changelog/' },
];

const trails = sidebarTrails(sidebar, '/docs/');

const trail = (contentPath) =>
  trailFor(
    {
      slug: contentPath.replace(/(^|\/)index\.mdx$/, '').replace(/\.mdx$/, ''),
      contentPath,
    },
    trails,
  );

test('a page the sidebar names outright keeps its own trail', () => {
  assert.deepEqual(trail('guides/start.mdx'), ['Guides']);
  assert.deepEqual(trail('index.mdx'), []);
  assert.deepEqual(trail('changelog/index.mdx'), []);
});

test('an autogenerated entry takes the label of the group it sits in', () => {
  assert.deepEqual(trail('reference/api.mdx'), ['Reference']);
  assert.deepEqual(trail('guides/kernels/conv.mdx'), ['Guides']);
});

test('a directory inside an autogenerated entry becomes a label of its own', () => {
  assert.deepEqual(trail('reference/c/nnconv.mdx'), ['Reference', 'c']);
  assert.deepEqual(trail('reference/c/index.mdx'), ['Reference', 'c']);
});

test('the deepest autogenerated entry claims the page', () => {
  assert.deepEqual(trail('guides/kernels/deep/conv.mdx'), ['Guides', 'deep']);
});

test('a page under no entry at all is still unclaimed', () => {
  assert.equal(trail('loose/page.mdx'), null);
  assert.deepEqual(trails.autogenerated, [
    { directory: 'guides/kernels', trail: ['Guides'] },
    { directory: 'reference', trail: ['Reference'] },
  ]);
});
