// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2026, Ambiq
import { useState } from 'react';
import { toast } from 'sonner';

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@ambiqai/helia-ui/react/accordion';
import { Button } from '@ambiqai/helia-ui/react/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@ambiqai/helia-ui/react/card';
import { Input } from '@ambiqai/helia-ui/react/input';
import { Label } from '@ambiqai/helia-ui/react/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@ambiqai/helia-ui/react/select';
import { Toaster } from '@ambiqai/helia-ui/react/sonner';
import { Switch } from '@ambiqai/helia-ui/react/switch';

const engines = [
  { value: 'rt', label: 'heliaRT' },
  { value: 'aot', label: 'heliaAOT' },
  { value: 'tflm', label: 'TFLM reference' },
];

const boards = [
  { value: 'apollo510', label: 'Apollo510 EVB' },
  { value: 'apollo4', label: 'Apollo4 Plus EVB' },
];

const strategies = [
  { value: 'balanced', label: 'Balanced' },
  { value: 'minimum', label: 'Minimum footprint' },
  { value: 'latency', label: 'Prefer latency' },
];

export default function FormDepthShowcase() {
  const [advanced, setAdvanced] = useState(false);

  return (
    <div className="not-content flex flex-col gap-4">
      <Card>
        <CardHeader>
          <CardTitle>Field depth</CardTitle>
        </CardHeader>
        <CardContent className="grid gap-4 md:grid-cols-3">
          <div className="flex flex-col gap-2">
            <Label htmlFor="depth-project">Project name</Label>
            <Input id="depth-project" defaultValue="apollo-voice" />
            <p className="text-xs text-muted-foreground">
              Used for the output directory.
            </p>
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="depth-arena">Tensor arena</Label>
            <Input id="depth-arena" defaultValue="640" aria-invalid />
            {/* Validation sits beside the field it belongs to, not at the
                top of the form, so the fix and the message are one glance. */}
            <p className="text-xs text-destructive">
              Enter a value between 64 and 512 KB.
            </p>
          </div>
          <div className="flex flex-col gap-2">
            <Label htmlFor="depth-manifest">Manifest label</Label>
            <Input
              id="depth-manifest"
              defaultValue="Generated by heliaRT"
              readOnly
            />
            <p className="text-xs text-muted-foreground">
              System-managed value.
            </p>
          </div>
        </CardContent>
      </Card>

      <form
        onSubmit={(event) => {
          event.preventDefault();
          toast('Deployment profile saved');
        }}
      >
        <Card>
          <CardHeader>
            <CardTitle>Deployment profile</CardTitle>
            <CardDescription>
              Group related fields and reveal specialist settings only when
              needed.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="flex flex-col gap-2">
                <Label htmlFor="profile-model">Model</Label>
                <Input
                  id="profile-model"
                  defaultValue="speech_enhancement.tflite"
                />
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="profile-engine">Deployment engine</Label>
                <Select defaultValue="rt">
                  <SelectTrigger id="profile-engine" className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {engines.map((engine) => (
                      <SelectItem key={engine.value} value={engine.value}>
                        {engine.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="profile-board">Target board</Label>
                <Select defaultValue="apollo510">
                  <SelectTrigger id="profile-board" className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {boards.map((board) => (
                      <SelectItem key={board.value} value={board.value}>
                        {board.label}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="flex flex-col gap-2">
                <Label htmlFor="profile-output">Output directory</Label>
                <Input id="profile-output" defaultValue="build/generated" />
                <p className="text-xs text-muted-foreground">
                  Relative to the project root.
                </p>
              </div>
            </div>

            <div className="flex items-center gap-2 border-t border-border pt-4">
              <Switch
                id="profile-advanced"
                checked={advanced}
                onCheckedChange={setAdvanced}
              />
              <Label htmlFor="profile-advanced">Advanced memory settings</Label>
            </div>

            {/* Revealing the section leaves the fields above untouched: the
                disclosure is additive, never a re-render of the whole form. */}
            {advanced && (
              <div className="grid gap-4 sm:grid-cols-2">
                <div className="flex flex-col gap-2">
                  <Label htmlFor="advanced-arena">Arena budget</Label>
                  <Input id="advanced-arena" type="number" defaultValue="192" />
                </div>
                <div className="flex flex-col gap-2">
                  <Label htmlFor="advanced-strategy">Memory strategy</Label>
                  <Select defaultValue="balanced">
                    <SelectTrigger id="advanced-strategy" className="w-full">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {strategies.map((strategy) => (
                        <SelectItem key={strategy.value} value={strategy.value}>
                          {strategy.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
            )}

            <Accordion type="single" collapsible>
              <AccordionItem value="serialization">
                <AccordionTrigger>What gets written</AccordionTrigger>
                <AccordionContent>
                  Firmware sources, model data, and a generated manifest, all
                  under the output directory named above.
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </CardContent>
          <CardFooter className="justify-end gap-2">
            <Button type="button" variant="ghost">
              Reset
            </Button>
            <Button type="submit">Save profile</Button>
          </CardFooter>
        </Card>
      </form>

      <Toaster />
    </div>
  );
}
